Fix error "AttributeError: 'RNA_Types' object has no attribute 'YAFA_V3_RENDER'" in recent development Blender 2.79.1-git code As reported in http://www.yafaray.org/community/forum/viewtopic.php?f=12&t=5266&start=15 Recent git development versions of Blender 2.79.1-git do not allow anymore to add custom types. Therefore the 3D view code was no longer working with them.
I have decided, for now, to create global variables to emulate the same functionality. I don't like to abuse global variables but I think in this case it could be justified. It seems to work for now, but let's keep an eye on this.